# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ba3f3dd9cbe006968d553cd1c45de573365ec6600f2d518adb21b79ce4ee2938d92841ba74e27de0ac6e1c452e684fdee2d2409603185cbb6359320540ab55

test:
  secret_key_base: f056567251379456c1d57e6de45f3e94d15f33cae11afae9b6d5e750412d18767fb1f8c48d200034f9e245c76a77562c55ed04083d7a1f0b66f1dd96b96c6ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
